# -*- coding: utf-8 -*-
"""BitLora158_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tdOd0MzkcIBN5h85LiVjzV77j7mvVx0S
"""

#Author: Vishnuprasad Pradeepkumar Reshma
!pip install -q transformers datasets accelerate trl

import torch
import torch.nn as nn
import torch.nn.functional as F
import math



from transformers import AutoModelForCausalLM, AutoTokenizer

model_id = "Qwen/Qwen2.5-1.5B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    torch_dtype=torch.float16,
    device_map="auto",
    low_cpu_mem_usage=True
)



from tqdm import tqdm
from datasets import load_dataset

def calculate_perplexity(model, tokenizer, dataset_name="roneneldan/TinyStories", split="validation[:100]"):
    print(f"loading benchmark dataset: {dataset_name} ({split})...")
    test_ds = load_dataset(dataset_name, split=split)

    model.eval()
    nlls = []
    max_length = 256

    for entry in tqdm(test_ds):
        encodings = tokenizer(entry["text"], return_tensors="pt", truncation=True, max_length=max_length).to("cuda")
        target_ids = encodings.input_ids.clone()

        with torch.no_grad():
            outputs = model(encodings.input_ids, labels=target_ids)
            neg_log_likelihood = outputs.loss

        nlls.append(neg_log_likelihood)

    # calculate perplexity
    ppl = torch.exp(torch.stack(nlls).mean())
    return ppl.item()

def run_lambada_accuracy(model, tokenizer, num_samples=100):
    dataset = load_dataset("cimec/lambada", split="test", trust_remote_code=True).select(range(num_samples))
    correct = 0

    for sample in dataset:
        text = sample["text"]
        words = text.split()
        context = " ".join(words[:-1])
        target_word = words[-1]

        inputs = tokenizer(context, return_tensors="pt").to("cuda")
        with torch.no_grad():
            outputs = model(**inputs)
            next_token_logits = outputs.logits[0, -1, :]
            predicted_token_id = torch.argmax(next_token_logits).item()
            predicted_word = tokenizer.decode(predicted_token_id).strip()

        if predicted_word.lower() == target_word.lower():
            correct += 1

    accuracy = (correct / num_samples) * 100
    print(f"\nBenchmark Result - Next-word Accuracy: {accuracy:.2f}%")

import time

def benchmark_speed_and_memory(model, tokenizer, prompt="Once upon a time"):
    inputs = tokenizer(prompt, return_tensors="pt").to("cuda")

    _ = model.generate(**inputs, max_new_tokens=5, pad_token_id=tokenizer.eos_token_id)

    torch.cuda.reset_peak_memory_stats()

    start_time = time.time()
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=100,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id
        )
    end_time = time.time()

    total_tokens = len(outputs[0]) - len(inputs.input_ids[0])
    duration = end_time - start_time
    tokens_per_second = total_tokens / duration
    peak_vram = torch.cuda.max_memory_allocated() / (1024 ** 3) # Convert to GB

    print(f"Generation Speed : {tokens_per_second:.2f} tokens/sec")
    print(f"Peak VRAM Usage  : {peak_vram:.2f} GB")

# Run the benchmark
perplexity_model = calculate_perplexity(model, tokenizer)
print('----------fp model perplexity-----------')
print('fp model perplexity:', perplexity_model)
print('------------------------------------------------------------------------------')
print('fp model accuracy')
run_lambada_accuracy(model, tokenizer)
print('------------------------------------------------------------------------------')
print('fp model speed and memory usage')
benchmark_speed_and_memory(model, tokenizer)
print('------------------------------------------------------------------------------')

del model
torch.cuda.empty_cache()

values_per_item = 4

def pack_weights(quantized_weights: torch.Tensor) -> torch.Tensor:
    original_shape = quantized_weights.shape
    row_dim = (original_shape[0] + values_per_item - 1) // values_per_item
    packed_tensor_shape = (row_dim,) if len(original_shape) == 1 else (row_dim, *original_shape[1:])

    quantized_weights = quantized_weights.clone() + 1
    packed = torch.zeros(packed_tensor_shape, device=quantized_weights.device, dtype=torch.uint8)
    unpacked = quantized_weights.to(torch.uint8)

    it = min(values_per_item, (original_shape[0] // row_dim) + 1)
    for i in range(it):
        start = i * row_dim
        end = min(start + row_dim, original_shape[0])
        packed[: (end - start)] |= unpacked[start:end] << (2 * i)
    return packed

def unpack_weights(packed: torch.Tensor, dtype: torch.dtype) -> torch.Tensor:
    packed_shape = packed.shape
    original_row_dim = packed_shape[0] * values_per_item
    unpacked_shape = (original_row_dim,) if len(packed_shape) == 1 else (original_row_dim, *packed_shape[1:])

    unpacked = torch.zeros(unpacked_shape, device=packed.device, dtype=torch.uint8)
    for i in range(values_per_item):
        start = i * packed_shape[0]
        end = start + packed_shape[0]
        mask = 3 << (2 * i)
        unpacked[start:end] = (packed & mask) >> (2 * i)
    return unpacked.to(dtype) - 1

class BitNetLoraLinear(nn.Module):
    def __init__(self, in_features, out_features, bias=False, r=8, lora_alpha=16, target_dtype=torch.float32):
        super().__init__()
        self.in_features = in_features
        self.out_features = out_features
        self.target_dtype = target_dtype
        self.r = r
        self.scaling = lora_alpha / r

        packed_out_features = (out_features + values_per_item - 1) // values_per_item
        self.register_buffer("packed_base_weight", torch.zeros((packed_out_features, in_features), dtype=torch.uint8))
        self.register_buffer("weight_scale", torch.ones((1, 1), dtype=target_dtype))

        self.bias = nn.Parameter(torch.zeros((out_features,), dtype=target_dtype)) if bias else None
        self.lora_A = nn.Parameter(torch.zeros((r, in_features), dtype=target_dtype))
        self.lora_B = nn.Parameter(torch.zeros((out_features, r), dtype=target_dtype))

        nn.init.kaiming_uniform_(self.lora_A, a=math.sqrt(5))
        nn.init.zeros_(self.lora_B)

    def forward(self, x):
        input_dtype = x.dtype
        x = x.to(self.target_dtype)

        base_weight = unpack_weights(self.packed_base_weight, dtype=self.target_dtype)[:self.out_features, :]
        base_output = F.linear(x, base_weight * self.weight_scale, self.bias)

        lora_output = F.linear(F.linear(x, self.lora_A), self.lora_B) * self.scaling
        return (base_output + lora_output).to(input_dtype)

def convert_to_bitnet_lora(model, r=8, lora_alpha=16):
    for name, module in list(model.named_modules()):
        if isinstance(module, nn.Linear) and not any(ex in name for ex in ["embed_tokens", "lm_head"]):
            device = module.weight.device

            orig_w = module.weight.data
            scale = orig_w.abs().mean().clamp(min=1e-5)
            ternary_w = (orig_w / scale).round().clamp(-1, 1)

            new_layer = BitNetLoraLinear(module.in_features, module.out_features, module.bias is not None, r, lora_alpha, torch.float32).to(device)

            with torch.no_grad():
                new_layer.packed_base_weight.copy_(pack_weights(ternary_w))
                new_layer.weight_scale.copy_(scale.to(torch.float32))
                if module.bias is not None:
                    new_layer.bias.copy_(module.bias.data.to(torch.float32))

            model.set_submodule(name, new_layer)
    return model

bit_model = AutoModelForCausalLM.from_pretrained(
    model_id,
    torch_dtype=torch.float16,
    device_map="auto"
)

bitlora_model = convert_to_bitnet_lora(bit_model, r=32, lora_alpha=64)



from google.colab import drive
import os
drive.mount('/content/drive')
saved_path = "/content/drive/MyDrive/BitNet_LoRA_Models/bitnet_qwen_lora_adapters.pt"
trained_weights = torch.load(saved_path, map_location="cuda")

bitlora_model.load_state_dict(trained_weights, strict=False)
bitlora_model.eval()

print(" bitlora model successfully loaded from google drive")

perplexity_model = calculate_perplexity(bitlora_model, tokenizer)
print('----------Bitlora model perplexity-----------')
print('Bitlora model perplexity:', perplexity_model)
print('------------------------------------------------------------------------------')
print('Bitlora model accuracy')
run_lambada_accuracy(bitlora_model, tokenizer)
print('------------------------------------------------------------------------------')
print('Bitlora model speed and memory usage')
benchmark_speed_and_memory(bitlora_model, tokenizer)
print('------------------------------------------------------------------------------')
'''
To see a dramatic drop in VRAM and a spike in generation tokens/sec,
I would need to compile custom CUDA kernels that can do matrix multiplication directly on packed integers without unpacking them first.
'''