# -*- coding: utf-8 -*-
"""BitLora158.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LKJngZeufzsxZflkU5luZ2w37g3tpl1D
"""

#Author: Vishnuprasad Pradeepkumar Reshma
!pip install -q transformers datasets accelerate trl

import torch
import torch.nn as nn
import torch.nn.functional as F
import math

values_per_item = 4

def pack_weights(quantized_weights: torch.Tensor) -> torch.Tensor:
    original_shape = quantized_weights.shape
    row_dim = (original_shape[0] + values_per_item - 1) // values_per_item
    packed_tensor_shape = (row_dim,) if len(original_shape) == 1 else (row_dim, *original_shape[1:])

    quantized_weights = quantized_weights.clone() + 1
    packed = torch.zeros(packed_tensor_shape, device=quantized_weights.device, dtype=torch.uint8)
    unpacked = quantized_weights.to(torch.uint8)

    it = min(values_per_item, (original_shape[0] // row_dim) + 1)
    for i in range(it):
        start = i * row_dim
        end = min(start + row_dim, original_shape[0])
        packed[: (end - start)] |= unpacked[start:end] << (2 * i)
    return packed

def unpack_weights(packed: torch.Tensor, dtype: torch.dtype) -> torch.Tensor:
    packed_shape = packed.shape
    original_row_dim = packed_shape[0] * values_per_item
    unpacked_shape = (original_row_dim,) if len(packed_shape) == 1 else (original_row_dim, *packed_shape[1:])

    unpacked = torch.zeros(unpacked_shape, device=packed.device, dtype=torch.uint8)
    for i in range(values_per_item):
        start = i * packed_shape[0]
        end = start + packed_shape[0]
        mask = 3 << (2 * i)
        unpacked[start:end] = (packed & mask) >> (2 * i)
    return unpacked.to(dtype) - 1

class BitNetLoraLinear(nn.Module):
    def __init__(self, in_features, out_features, bias=False, r=8, lora_alpha=16, target_dtype=torch.float32):
        super().__init__()
        self.in_features = in_features
        self.out_features = out_features
        self.target_dtype = target_dtype
        self.r = r
        self.scaling = lora_alpha / r

        packed_out_features = (out_features + values_per_item - 1) // values_per_item
        self.register_buffer("packed_base_weight", torch.zeros((packed_out_features, in_features), dtype=torch.uint8))
        self.register_buffer("weight_scale", torch.ones((1, 1), dtype=target_dtype))

        self.bias = nn.Parameter(torch.zeros((out_features,), dtype=target_dtype)) if bias else None
        self.lora_A = nn.Parameter(torch.zeros((r, in_features), dtype=target_dtype))
        self.lora_B = nn.Parameter(torch.zeros((out_features, r), dtype=target_dtype))

        nn.init.kaiming_uniform_(self.lora_A, a=math.sqrt(5))
        nn.init.zeros_(self.lora_B)

    def forward(self, x):
        input_dtype = x.dtype
        x = x.to(self.target_dtype)

        base_weight = unpack_weights(self.packed_base_weight, dtype=self.target_dtype)[:self.out_features, :]
        base_output = F.linear(x, base_weight * self.weight_scale, self.bias)

        lora_output = F.linear(F.linear(x, self.lora_A), self.lora_B) * self.scaling
        return (base_output + lora_output).to(input_dtype)

def convert_to_bitnet_lora(model, r=8, lora_alpha=16):
    for name, module in list(model.named_modules()):
        if isinstance(module, nn.Linear) and not any(ex in name for ex in ["embed_tokens", "lm_head"]):
            device = module.weight.device

            orig_w = module.weight.data
            scale = orig_w.abs().mean().clamp(min=1e-5)
            ternary_w = (orig_w / scale).round().clamp(-1, 1)

            new_layer = BitNetLoraLinear(module.in_features, module.out_features, module.bias is not None, r, lora_alpha, torch.float32).to(device)

            with torch.no_grad():
                new_layer.packed_base_weight.copy_(pack_weights(ternary_w))
                new_layer.weight_scale.copy_(scale.to(torch.float32))
                if module.bias is not None:
                    new_layer.bias.copy_(module.bias.data.to(torch.float32))

            model.set_submodule(name, new_layer)
    return model

from transformers import AutoModelForCausalLM, AutoTokenizer

model_id = "Qwen/Qwen2.5-1.5B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    torch_dtype=torch.float16,
    device_map="auto",
    low_cpu_mem_usage=True
)

#model = convert_to_bitnet_lora(model, r=8, lora_alpha=16)
model = convert_to_bitnet_lora(model, r=32, lora_alpha=64)

for name, param in model.named_parameters():
    param.requires_grad = "lora_" in name

print(f"Trainable parameters: {sum(p.numel() for p in model.parameters() if p.requires_grad):,}")

from datasets import load_dataset
from transformers import TrainingArguments, Trainer, DataCollatorForLanguageModeling

# load a tiny text dataset
dataset = load_dataset("roneneldan/TinyStories", split="train[:10000]")

def tokenize_function(examples):
    return tokenizer(examples["text"], truncation=True, max_length=256)

tokenized_dataset = dataset.map(tokenize_function, batched=True, remove_columns=["text"])
tokenizer.pad_token = tokenizer.eos_token

training_args = TrainingArguments(
    output_dir="./colab_bitnet_lora",
    #learning_rate=3e-4,
    learning_rate=5e-4,
    #per_device_train_batch_size=2,
    per_device_train_batch_size=4,  #keep small to avoid OOM
    #gradient_accumulation_steps=8,
    gradient_accumulation_steps=4,
    num_train_epochs=4,
    #num_train_epochs=3,
    #logging_steps=5,
    logging_steps=10,
    fp16=True,
    gradient_checkpointing=True,
    save_strategy="no",
    report_to="none"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset,
    data_collator=DataCollatorForLanguageModeling(tokenizer, mlm=False),
)

trainer.train()

model.eval()

prompt = "Once upon a time, there was a little bird who wanted to"
inputs = tokenizer(prompt, return_tensors="pt").to("cuda")

with torch.no_grad():
    outputs = model.generate(
        **inputs,
        max_new_tokens=100,
        do_sample=True,
        temperature=0.3,
        top_p=0.85,
        repetition_penalty=1.2,
        pad_token_id=tokenizer.eos_token_id
    )
print(tokenizer.decode(outputs[0], skip_special_tokens=True))

def inspect_bitnet_quantization(model):

    total_layers_checked = 0
    quantized_layers_count = 0

    for name, module in model.named_modules():
        if module.__class__.__name__ == "BitNetLoraLinear":
            total_layers_checked += 1

            packed_weight = module.packed_base_weight
            weight_scale = module.weight_scale

            packed_shape = list(packed_weight.shape)
            unpacked_out_features = module.out_features
            in_features = module.in_features

            raw_sample = packed_weight[:2, :3].tolist()

            from __main__ import unpack_weights
            unpacked_weight_sample = unpack_weights(packed_weight[:1, :], dtype=torch.float32)
            ternary_values_sample = unpacked_weight_sample[0, :8].tolist()

            if quantized_layers_count < 3:
                print(f"Layer: {name}")
                print(f"Storage Data Type : {packed_weight.dtype}")
                print(f"Expected Linear Dimensions : [{unpacked_out_features} x {in_features}]")
                print(f"Actual Packed Storage Shape: {packed_shape}")
                print(f"Raw Memory Values Sample: {raw_sample}")
                print(f"Unpacked Ternary Values: {ternary_values_sample} (Should only be -1.0, 0.0, or 1.0)")
                print(f"Quantization Scale Factor: {weight_scale.item():.6f}")
                print("-" * 50)

            quantized_layers_count += 1

    print(f"\nSummary:")
    print(f"Successfully located and verified {quantized_layers_count} out of {total_layers_checked} BitNet layers.")
    if quantized_layers_count > 0:
        print("Weights are quantized")
    else:
         print("No packed BitNet layers found")

inspect_bitnet_quantization(model)

from google.colab import drive
import os
drive.mount('/content/drive')
save_dir = '/content/drive/MyDrive/BitNet_LoRA_Models'
os.makedirs(save_dir, exist_ok=True)

lora_state_dict = {name:param for name,param in model.named_parameters() if 'lora_' in name or 'bias' in name}
save_path = os.path.join(save_dir, 'bitnet_qwen_lora_adapters.pt')
torch.save(lora_state_dict, save_path)
print(f" successfully saved {len(lora_state_dict)} trained parameters to google drive at: {save_path}")

